//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleverWidget.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CleverWidget.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template project for Widget plugins.
        /// </summary>
        public static string CleverWidget_Description {
            get {
                return ResourceManager.GetString("CleverWidget_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clever Widget.
        /// </summary>
        public static string CleverWidget_Name {
            get {
                return ResourceManager.GetString("CleverWidget_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary BG Color.
        /// </summary>
        public static string WidgetThemeControls_PrimaryBackgroundColor {
            get {
                return ResourceManager.GetString("WidgetThemeControls_PrimaryBackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary FG Color.
        /// </summary>
        public static string WidgetThemeControls_PrimaryForegroundColor {
            get {
                return ResourceManager.GetString("WidgetThemeControls_PrimaryForegroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary BG Color.
        /// </summary>
        public static string WidgetThemeControls_SecondaryBackgroundColor {
            get {
                return ResourceManager.GetString("WidgetThemeControls_SecondaryBackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary FG Color.
        /// </summary>
        public static string WidgetThemeControls_SecondaryForegroundColor {
            get {
                return ResourceManager.GetString("WidgetThemeControls_SecondaryForegroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Global Theme.
        /// </summary>
        public static string WidgetThemeControls_UseGlobalTheme {
            get {
                return ResourceManager.GetString("WidgetThemeControls_UseGlobalTheme", resourceCulture);
            }
        }
    }
}
